### ISSUE TITLE
blinds Nice (niceforyou)

### ISSUE THREAD

**Issue by turuwhiska** [nickw444/homekit#40]
hi i have a motor blind Nice . the controls are ergo1 only have 3 buttons. dont have information for the protocol only say 433.92 rolling code 52 bits. i will try your metod, you think is posible to work?

**Comment by turuwhiska** [comment]
Thank you for your answer. Yes, the page information says rolling code 52 bits.
I think that in this protocol, a part of the data changes and others remain constant. Is this so?
The control has 3 buttons, up, down, stop. I imagine that some part of the data identifies the button.
I saw some rolling codes like Dooya, Somfy (433.42), but I did not see any specific for www.niceforyou.com
Do you think any of these could work?
Thanks a lot

**Comment by nickw444** [comment]
Hi @turuwhiska thanks for posting all of that information. Unfortunately without more data or physical access to these remotes I don't think I can be of much assistance.

**Comment by turuwhiska** [comment]
Yes, it is a problem, because there is not much information.
I have physical access to the remote control and the curtain, the chip is an MCHC908
If you have any idea how to get information tell me I will continue testing
Here is some protocol information (in Russian, you can use the translator)
https://web.archive.org/web/20180807004652/http://phreakerclub.com

**Comment by turuwhiska** [comment]
Yes, it is a problem, because there is not much information.
I have physical access to the remote control and the curtain, the chip is an MCHC908
If you have any idea how to get information tell me I will continue testing
Here is some protocol information (in Russian, you can use the translator)
https://web.archive.org/web/20180807004652/http://phreakerclub.com

**Comment by peros550** [comment]
Did anyone had luck with niceforyou protocol ?
