### ISSUE TITLE
Help needed with Blindkit - blind remote codes and transmit.ino

### ISSUE THREAD

**Issue by plasticbrain777** [nickw444/homekit#48]
Hi Nick,
I'm not sure what processing I need to do with the captured RF codes from my RAEX/spotlight blind remote, in order to use them with transmit.ino.  I have captured all required codes using receive_manchester.ino 

e.g Capture 2 UP:
00000001100010001101110100100000000010101
00000001100010001101110100100000000010101
00000001100010001101110100100000000010101

e.g. Arduino code:
const char * code = "00000001100010001101110100100000000010101"; // 2 UP

I've tried putting one or three repeated strings of these captures into transmit.ino, and the board+RFTX definitely transmits, but the blinds don't react.  My captured string is shorter than the one in the original code, so I assume I'm missing something.
Any pointers would be much appreciated :-)
Cheers,
Plasticbrain777

**Comment by nickw444** [comment]
Hi @plasticbrain777, the capture/transmit sketches are actually not very useful, and in fact the receive one `receive_manchester` didn't work for me when reverse engineering the protocol.

I have a full blown ESP8266 firmware you can use ([`esp-blindkit`](https://github.com/nickw444/homekit/tree/master/esp-fw/esp-blindkit)), which connects via MQTT and supports sending codes and pairing commands. I use this with my home-assistant setup at the moment:

https://github.com/nickw444/homekit/blob/947f3859d72ef1c2bdcc8a1ed877a5e5fbb3af9f/home-assistant/conf/components/blindkit/covers.yaml#L1-L8

Alternatively, if you have a [broadlink RM Pro](http://www.ibroadlink.com/rmPro+/), you can generate commands for your blinds using this tool, which also integrates with homekit if you want to avoid MQTT.

Additionally, I have a tool which can be used to generate the remote codes (raw), which you can find here: https://github.com/nickw444/homekit/tree/master/blindkit/remote-gen. You could use these in a custom transmit firmware if you felt like going down that path. 

Hope this helps.

**Comment by plasticbrain777** [comment]
Thanks for that Nick... funnily enough I gave up on the receive_manchester.ino/transmit.ino code, and tried the ESP8266 firmware last night - it works great!  (should have tried that one first).  

I was hoping to clone my remote, but failing that, I just paired the blinds with new codes form the ESP8266.  The remote still works as well because the blinds can pair with multiple remotes.

Thanks again for spending the time to publish your work.
Cheers 👍

**Comment by nickw444** [comment]
Awesome, glad to know you figured it out. I should probably make this clearer for other people landing here in the future - I had another person with a similar story, where I helped them over email. 

Anyway, I will close this issue since it seems you're all sorted. Feel free to open a new issue (or comment here) if there's anything 🌮
